platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MJExtension', '~> 2.5.14'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJRefresh', '~> 2.4.12'
pod 'RegexKitLite', '~> 4.0'
pod 'FMDB', '~> 2.5'